### ISSUE TITLE
Command run every 30 minute on specific day

### ISSUE THREAD

**Issue by phantasyy** [thomasleveil/b3-plugin-scheduler#2]
Is it possible to make a command run every 30 min on a specific day of a week (monday ) for example. I noticed it's possible to make like     
<cron name="everyMondayMorningAt7am" minutes="0" hour="7" dow="1">

but it just spams at 7 AM  and no more.

**Comment by thomasleveil** [comment]
what's in your config file?

**Comment by phantasyy** [comment]
https://hastebin.com/yetocoveda.xml

**Comment by thomasleveil** [comment]
try this:

```
    <cron name="everyMondayMorningAt7am" minutes="*/30" hour="7" dow="1">
        <rcon>bigtext "^7Of cours it's monday... Does this look like my friday face? -_-'"</rcon>
    </cron>
```

**Comment by phantasyy** [comment]
But that will just write it 7 in the morning and not just every 30 min on monday?

**Comment by thomasleveil** [comment]
ok, then

```
    <cron name="everyMondayMorningAt7am" minutes="*/30" hour="7-23" dow="1">
        <rcon>bigtext "^7Of cours it's monday... Does this look like my friday face? -_-'"</rcon>
    </cron>
```
should display your message every 30 minutes, on mondays, from 7am to 11pm

**Comment by phantasyy** [comment]
Looks nice, thanks for the help!
